spring.application.name=demo
server.port=8086
#spring.datasource.url=jdbc:mysql://localhost:3307/nov9sql?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://localhost:3307/nov9sql
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
###################################eureka
# ==============================
# EUREKA CLIENT CONFIGURATION
# ==============================

# Register this client in Eureka using its IP address
# instead of the computer name (hostname).
#
# Example:
# Hostname  : DESKTOP-ABCD123
# IP Address: 192.168.1.20
#
# If true, Eureka stores the IP.
# If false, Eureka stores the hostname.
#
# Mostly kept true because IP is easier for other services
# to connect to.
eureka.instance.prefer-ip-address=true


# Download the registry (list of all registered microservices)
# from Eureka Server.
#
# Imagine Eureka is a phonebook.
#
# User Service asks:
# "Give me the list of all services."
#
# Eureka sends:
#
# User-Service
# Hotel-Service
# Rating-Service
#
# Now this client knows where every service is.
#
# Since this client needs to call other services,
# we keep it true.
eureka.client.fetch-registry=true


# Register this application inside Eureka.
#
# Imagine a new student joins school.
#
# Student says:
# "Please write my name in the attendance register."
#
# Similarly this client says:
#
# "Hello Eureka,
# My name is User Service.
# Please register me."
#
# Eureka stores it in its registry.
#
# Therefore keep it true.
eureka.client.register-with-eureka=true


# Tell this client where the Eureka Server is running.
#
# localhost = this same computer
# 8761      = Eureka Server's port
# /eureka   = Eureka's registration endpoint
#
# Whenever this application starts,
# it contacts this URL to:
#
# 1. Register itself.
# 2. Download the registry.
#
# Think of this as Eureka Server's address.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


##############Configuring git config server#################
spring.config.import=optional:configserver:http://localhost:9873



